apiVersion: v1
kind: Service
metadata:
  name: petsi-public-service
spec:
  selector:
    app.kubernetes.io/instance: 'petsiapp'
    app.kubernetes.io/name: 'petsi-back'
    color: 'blue'
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  type: LoadBalancer
  loadBalancerIP: 20.74.24.140
